name: CentOS7 Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: yum install python3 python3-pip
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Build Python project
        run: python3 discordbot.py build
      - name: Deploy Python project
        run: python3 discordbot.py deploy
