name: CentOS7 Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: centos-7

    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: yum install python3 python3-pip
      - name: Run and nohup discordbot
        run: nohup python3.9 /var/git/discordpy-startup/discordbot.py &
